factorial : factorial.c
	gcc -o ../obj/factorial factorial.c

power : power.c
	gcc -o ../obj/power power.c

fibonacci : fibonacci.c
	gcc -o ../obj/fibonacci fibonacci.c

printstring : printstring.c
	gcc -o ../obj/printstring printstring.c

printstring_desc : printstring_desc.c
	gcc -o ../obj/printstring_desc printstring_desc.c

binarycalculator : binarycalculator.c
	gcc -o ../obj/binarycalculator binarycalculator.c

sum : sum.c
	gcc -o ../obj/sum sum.c

saveinttoarray : saveinttoarray.c
	gcc -o ../obj/saveinttoarray saveinttoarray.c

search : search.c
	gcc -o ../obj/search search.c
	
searchmaxvalue : searchmaxvalue.c
	gcc -o ../obj/searchmaxvalue searchmaxvalue.c

binarysearch : binarysearch.c
	gcc -o ../obj/binarysearch binarysearch.c

maze : maze.c
	gcc -o ../obj/maze maze.c