bubblesort : bubblesort.c
	gcc -o ../../obj/bubblesort bubblesort.c

selectionsort : selectionsort.c
	gcc -o ../../obj/selectionsort selectionsort.c

insertionsort : insertionsort.c
	gcc -o ../../obj/insertionsort insertionsort.c

mergesort : mergesort.c
	gcc -o ../../obj/mergesort mergesort.c

quicksort : quicksort.c
	gcc -o ../../obj/quicksort quicksort.c

heapsort : heapsort.c
	gcc -o ../../obj/heapsort heapsort.c

priorityqueue : priorityqueue.c
	gcc -o ../../obj/priorityqueue priorityqueue.c
